
export const CAR_OF_THE_WEEK_REQUEST = 'home/CAR_OF_THE_WEEK_REQUEST'
export const CAR_OF_THE_WEEK_SUCCESS = 'home/CAR_OF_THE_WEEK_SUCCESS'
export const CAR_OF_THE_WEEK_FAILURE = 'home/CAR_OF_THE_WEEK_FAILURE'