export const SET_SELECTED_MAKE     = 'search/SET_SELECTED_MAKE'
export const GET_MAKE_LIST_REQUEST = 'search/GET_MAKE_LIST_REQUEST'
export const GET_MAKE_LIST_SUCCESS = 'search/GET_MAKE_LIST_SUCCESS'
export const GET_MAKE_LIST_FAILURE = 'search/GET_MAKE_LIST_FAILURE'

export const SET_SELECTED_MODEL     = 'search/SET_SELECTED_MODEL'
export const GET_MODEL_LIST_REQUEST = 'search/GET_MODEL_LIST_REQUEST'
export const GET_MODEL_LIST_SUCCESS = 'search/GET_MODEL_LIST_SUCCESS'
export const GET_MODEL_LIST_FAILURE = 'search/GET_MODEL_LIST_FAILURE'

export const GET_MODEL_DETAILS_REQUEST = 'search/GET_MODEL_DETAILS_REQUEST'
export const GET_MODEL_DETAILS_SUCCESS = 'search/GET_MODEL_DETAILS_SUCCESS'
export const GET_MODEL_DETAILS_FAILURE = 'search/GET_MODEL_DETAILS_FAILURE'